# Generated by Django 4.2.7 on 2025-11-25 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bike', 'Bike'), ('car_4seats', 'Car 4 Seats'), ('car_7seats', 'Car 7 Seats')], max_length=20, null=True)),
                ('vehicle_brand', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('license_plate', models.CharField(blank=True, max_length=20)),
                ('driver_license_number', models.CharField(blank=True, max_length=20)),
                ('drive_license_expiry', models.DateField(blank=True, null=True)),
                ('vehicle_registration_number', models.CharField(blank=True, max_length=20)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('approval_note', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('total_trips', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_online', models.BooleanField(default=False)),
                ('last_online_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver_profiles',
                'indexes': [models.Index(fields=['user'], name='driver_prof_user_id_7b11b9_idx'), models.Index(fields=['approval_status'], name='driver_prof_approva_816b0c_idx'), models.Index(fields=['license_plate'], name='driver_prof_license_99f1a2_idx')],
            },
        ),
    ]
